# Generated by Django 5.0.6 on 2025-11-04 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_alter_cita_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cumplio', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='citas.cita')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
