# Generated by Django 5.0.6 on 2025-10-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('primera', 'Primera vez'), ('seguimiento', 'Seguimiento')], default='primera', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistida', 'Asistida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
        ),
    ]
