# Generated by Django 5.0.6 on 2025-11-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora']},
        ),
    ]
