# Generated by Django 5.0.6 on 2025-11-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
