# Generated by Django 5.0.6 on 2025-11-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='notas',
            new_name='afirmacion',
        ),
        migrations.AddField(
            model_name='cita',
            name='nactividad_psicologica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
