# Generated by Django 5.0.6 on 2025-12-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_rename_notas_cita_afirmacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='nactividad_psicologica',
            new_name='actividad_psicologica',
        ),
    ]
